#!/usr/bin/env bash
WALLPAPER_DIR="$HOME/Documents/wallpapers/"
if [ "$1" ]; then
      if [ -r "$1" ]; then
          WALLPAPER="$1"
      else
          echo "Wallpaper not found or unreadable"
     fi
else
     CURRENT_WALL=$(hyprctl hyprpaper listloaded)

     # Get a random wallpaper that is not the current one
   WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)
fi

# Apply the selected wallpaper and update pywal
swww img "$WALLPAPER" --transition-type center --transition-duration 1.1 --transition-step 160
sleep 0.4 && wal -i "$WALLPAPER" -n

# Get wal colors to proceed with tweaks
highlight_color=$(sed '6q;d' ~/.cache/wal/colors)
background_color=$(sed '8q;d' ~/.cache/wal/colors)
border_color=$(sed '2q;d' ~/.cache/wal/colors)
midground_color=$(sed '7q;d' ~/.cache/wal/colors)

# Update pywalfox
pywalfox update

# Dunst notification colors have to be manually updated while dunst is killed
pkill dunst
sed -i --follow-symlinks "s|frame_color = \"#......\"|frame_color = \"${border_color}\"|" ~/.config/dunst/dunstrc || notify-send "faliure to change dunst border colors"
sed -i --follow-symlinks "s|background = \"#......\"|background = \"${background_color}\"|" ~/.config/dunst/dunstrc || notify-send "faliure to change dunst background colors"

# Since my powermenu is custom, I have to update the colors accordingly
pkill eww
sed -i --follow-symlinks "s|border-color: #......|border-color: ${border_color}|" ~/.config/eww/powermenu/powermenu.scss
sed -i --follow-symlinks "s|background-color: #......|background-color: ${background_color}|" ~/.config/eww/powermenu/powermenu.scss
sed -i --follow-symlinks "s|highlight-color: #......|highlight-color: ${highlight_color}|" ~/.config/eww/powermenu/powermenu.scss
sed -i --follow-symlinks "s|midground-color: #......|midground-color: ${midground_color}|" ~/.config/eww/powermenu/powermenu.scss
eww daemon

# Cava colors are updated aswell
sed -i --follow-symlinks "s|gradient_color_1 = '#......'|gradient_color_1 = '${highlight_color}'|" ~/.config/cava/config
sed -i --follow-symlinks "s|gradient_color_2 = '#......'|gradient_color_2 = '${midground_color}'|" ~/.config/cava/config
sed -i --follow-symlinks "s|gradient_color_3 = '#......'|gradient_color_3 = '${border_color}'|" ~/.config/cava/config
sed -i --follow-symlinks "s|gradient_color_4 = '#......'|gradient_color_4 = '${background_color}'|" ~/.config/cava/config


# Finally, the hyprland window border color is updated
sed -i --follow-symlinks "s|col.active_border = rgba(........)|col.active_border = rgba(${highlight_color//#}ee)|" ~/.config/hypr/hyprland.conf


