windowrulev = float, class:notes
windowrulev = size 30% 25% , class:notes
windowrulev = move 69% 04% , class:notes
windowrulev = pin  , class:notes
bind = $mainMod+Shift, N, exec, hyprctl clients | grep "class: notes" || kitty --class notes vim
